version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    links:
      - alertmanager:alertmanager
    restart: always
    deploy:
      mode: global
    ports:
      - 9090:9090
    depends_on:
      - acl

  node-exporter:
    image: prom/node-exporter
    command:
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global

  acl:
    build:
      dockerfile: dockerfile_acl
      context: .
    command: "/app/acl"
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:latest
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'
    ports:
      - 9093:9093
    depends_on:
      - telegram-alertmanager-bot

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - 9091:9091
    depends_on:
      - prometheus

  telegram-alertmanager-bot:
    image: moghaddas/prometheus_bot
    volumes:
      - ./telegram:/etc/telegram/
    command:
      - '-c=/etc/telegram/config.yml'
    ports:
      - 9087:9087