global:
  scrape_interval: 15s # как часто очищать цели
  evaluation_interval: 15s # смотрим, обновились ли правила
  external_labels:
    monitor: 'geekbrains'
rule_files:
  - "/etc/prometheus/rules.yml"
scrape_configs:
  - job_name: acl
    static_configs:
      - targets: ["acl:9090"]
  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
